### ISSUE TITLE
[bug] tairSearch.tftmadddoc 批量插入报错

### ISSUE THREAD

**Issue by dashiell-zhang** [alibaba/AlibabaCloud.TairSDK#25]
![image](https://github.com/tair-opensource/AlibabaCloud.TairSDK/assets/36178221/3607d391-b092-4de4-983e-827364461273)

tairSearch.tftadddoc 单个插入不会报错，但是批量插入会直接报错，userCaches 的值如下：

![image](https://github.com/tair-opensource/AlibabaCloud.TairSDK/assets/36178221/53e68519-b919-49c2-a86a-18a102b06090)

**Comment by Shuen14** [comment]
`tft.madddoc` 使用时必须指定每个 doc 的 docid （https://help.aliyun.com/document_detail/443821.html#section-jyu-b19-f35）
<img width="1335" alt="image" src="https://github.com/tair-opensource/AlibabaCloud.TairSDK/assets/106955810/fa0d5ae3-d9e7-417a-9267-daffbc4cb640">

可以参考`TairSearchTest`测试文件中的`tftmaddteststring`case.

**Comment by dashiell-zhang** [comment]
下午好，我现在调整之后可以了，是因为我之前默认认为字典的 key 应该就是 doc_id，没想到 tftmadddoc 方法竟然是反过来的逻辑，key 是 doc，value 是 doc_id，当入参是 字典时，习惯性的会认为 key 应该是 标识id，tftmadddoc 这里的入参逻辑有点奇怪
